### ISSUE TITLE
Resolve FE Package Vulnerabilities

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#1]
@Tomerozfresko - After installing the client, npm is warning me that there are 11 vulnerabilities in the packages installed, 2 of which are critical.

<img width="888" alt="Screenshot 2022-11-15 at 9 06 56 AM" src="https://user-images.githubusercontent.com/95449364/201982835-e47eda6f-ec78-49bb-8cdb-0f8745296248.png">

Run `npm audit` to see details about which packages include vulnerabilities.

IN A NEW BRANCH, run `npm audit fix` and/or `npm audit fix --force` to try and resolve vulnerabilities. Doing this in a new branch will protect your main branch just in case npm's audit fix introduces new problems.

Github's [Dependabot Alerts](https://github.com/Tomerozfresko/groupomania/security/dependabot) might also be able to rcatch/esolve some of these issues instead of using npm audit.

**Comment by Tomerozfresko** [comment]
@AccessiT3ch  

It was challenging. 

I am having now "only" **6 high severity_ vulnerabilities** after installing manually some libraries. 
running `npm audit fix --force` actually made things worse.  I'm having **4 critical_ vulnerabilities** after running this command. 
 
Any idea how to approach it better?

**Comment by AccessiT3ch** [comment]
> I'm having 4 critical_ vulnerabilities after running this command.

@Tomerozfresko - Oh that's fun, are you able to re-run the audit fix command to resolve those new vulnerabilities?

I would probably suggest discarding the changes made from the audit and google for more information about the 2 specific critical vulnerabilities. It could be that the known vulnerabilities won't actually affect your code, or there might be a more direct fix suggested by the community.

Worst case: ignore the vulnerabilities and move on 😄
