### ISSUE TITLE
Add parameter and usage comments to axios API function

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#10]
@Tomerozfresko - Even though [it's such a simple helper function](https://github.com/Tomerozfresko/groupomania/blob/master/client/src/axios.js#L7-L10), it can be very helpful to include comments directly above the function explaining its usage, required parameters, and return value. Doing so will help VS Code, Github, etc provide tooltips and render syntax warnings if the function is being used incorrectly.

**Comment by Tomerozfresko** [comment]
@AccessiT3ch  Done in [6341170](https://github.com/Tomerozfresko/groupomania/commit/63411706b06e771d3d96c74efff7c0fd58f9f783)
