### ISSUE TITLE
Share file upload error handling

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#11]
@Tomerozfresko - what happens [if a file fails to upload](https://github.com/Tomerozfresko/groupomania/blob/master/client/src/components/share/Share.jsx#L53) in the Share component? Is there error handling for this scenario? It looks like the upload function will catch the error but then only console logs it, is there any indication to the user that there was some sort of error?

Also, you can use `console.warn()` or `.error()` instead of `.log()` when logging warnings and errors.

**Comment by Tomerozfresko** [comment]
@AccessiT3ch Done in [9345aff](https://github.com/Tomerozfresko/groupomania/commit/9345affbf1720293ffc282e72016a3895de9f12d)
