### ISSUE TITLE
Default profile image 404s in post

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#4]
@Tomerozfresko it looks like my default "CO" profile image isn't rendering when I make a post.

<img width="738" alt="Screenshot 2022-11-15 at 9 26 46 AM" src="https://user-images.githubusercontent.com/95449364/201986332-e13b745e-3b21-426c-a47b-3c449e8dd548.png">

**Comment by Tomerozfresko** [comment]
Done in commit [aca97eb](https://github.com/Tomerozfresko/groupomania/commit/aca97eb090484203e8f4c90ee2a803a878d92716)
