### ISSUE TITLE
Prevent Empty Post Submissions

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#5]
@Tomerozfresko This was actually an accident, but it should probably be prevented! With `input` elements, we can set them to be disabled unless certain conditions are met (like if there's a photo and/or message included).

<img width="751" alt="Screenshot 2022-11-15 at 9 28 17 AM" src="https://user-images.githubusercontent.com/95449364/201987048-f3048cec-426d-4f52-8c7d-6c1b737aa65a.png">

**Comment by Tomerozfresko** [comment]
@AccessiT3ch Done in [faa23cb](https://github.com/Tomerozfresko/groupomania/commit/faa23cb6a7e734ed08f4eddb95601bbcd6af4393)
