### ISSUE TITLE
Cropped Image Posts

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#6]
@Tomerozfresko - I just uploaded a meme for a post, but it looks like it gets cropped by some object-fit styling, so in this case quite a bit of context was cut off with no way to show the full image. For example:

Cropped llamas, so cute!
<img width="673" alt="Screenshot 2022-11-15 at 9 37 12 AM" src="https://user-images.githubusercontent.com/95449364/201988463-22d5cb69-44be-4052-b483-d6b2da8f34e8.png">

Full llamas meme, omg thats funny!
<img width="752" alt="Screenshot 2022-11-15 at 9 37 42 AM" src="https://user-images.githubusercontent.com/95449364/201988740-441e56f8-78a9-4a27-aaf3-ee6cee997479.png">

**Comment by Tomerozfresko** [comment]
@AccessiT3ch Done in [6bbe14d](https://github.com/Tomerozfresko/groupomania/commit/6bbe14d621748dbd080ca4ea6e03f7702ec7a0d1)
