### ISSUE TITLE
Update SEO in public/index.html

### ISSUE THREAD

**Issue by AccessiT3ch** [Tomerozfresko/groupomania#7]
@Tomerozfresko - Right now it looks like the title tag and description meta tags are still the CRA defaults and should be updated.

- [ ] title tag shouldn't be "React App"
- [ ] meta:description tag should be something more descriptive
- [ ] favicon should be branded to match the site

Additional SEO meta data tags can be added as well, specifically `og:` tags.

**Comment by Tomerozfresko** [comment]
@AccessiT3ch Done in [f7f9539](https://github.com/Tomerozfresko/groupomania/commit/f7f9539d83d655c13431498b0d35dfdf9ba9c0de)
